### ISSUE TITLE
Percentage/count of accidents per {gender, age, time of day, day of week, month, severity, injury type, road user type, vehicle type} relative to other geo buckets

### ISSUE THREAD

**Issue by eliadl** [hasadna/anyway-data-science#20]
Description:
1. Create the data query 
2. Create the data plot
3. Drill down to account for statistical methodology.
   - normalization
   - significance
   - deeper analysis to understand data source with respect to visualization type
   - etc.

**Comment by elashahar01** [comment]
this will be done as part of use case investigations
